apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xsoar-server-pod
  name: xsoar-server-pod  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xsoar-server-pod
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/xsoar-server-pod: unconfined
      labels:
        app: xsoar-server-pod      
    spec:
      automountServiceAccountToken: false
      containers:
      - image: "{{ .Values.xsoar_image.repository }}:{{ .Values.xsoar_image.tag }}"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        name: xsoar-server-pod
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
          name: "https-webgui"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "16"
            github.com/fuse: "1"
            memory: 32Gi
          requests:
            cpu: "16"
            memory: 32Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/demisto
          mountPropagation: None
          name: xsoar-persistent-storage
        - mountPath: /usr/local/demisto/demisto.lic
          mountPropagation: None
          name: xsoar-lic
          subPath: demisto.lic
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
        runAsNonRoot: true
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 600
      volumes:
      - name: xsoar-lic
        configMap:
          defaultMode: 511
          name: xsoar-lic
          optional: false
      - name: xsoar-persistent-storage
        persistentVolumeClaim:
          claimName: xsoar-volume
      # optional config map for /etc/demisto.conf
      # - name: demisto-conf 
      #   configMap:
      #     defaultMode: 511
      #     name: demisto-conf
      #     optional: true
