name: Package DCO Foundation
run-name: ${{github.actor}} is building the DCO Foundation Zarf Package
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]
permissions:
  id-token: write
  contents: read
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-zarf
      - uses: ./.github/actions/package-create
      - uses: unfor19/install-aws-cli-action@v1.0.3
        with:
          version: 2 # default
          verbose: false # default
          arch: amd64 # allowed values: amd64, arm64
          rootdir: "" # defaults to "PWD"
          workdir: "" # defaults to "PWD/unfor19-awscli"
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.AWS_ROLE}}
          role-session-name: dco-foundation
          aws-region: us-east-1
      - uses: ./.github/actions/s3-publish
        with:
          aws_bucket: ${{secrets.AWS_BUCKET}}
          source: "zarf-package-suricata-amd64.tar.zst"
          destination: "${{github.repository}}/${{ github.head_ref || github.ref_name }}/zarf-package-suricata-amd64.tar.zst"
